-- MySQL Script generated by MySQL Workbench
-- 04/29/15 10:23:33
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema photo_album
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema photo_album
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `photo_album` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `photo_album` ;

-- -----------------------------------------------------
-- Table `photo_album`.`album_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `photo_album`.`album_types` (
  `id` INT PRIMARY KEY AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `photo_album`.`albums`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `photo_album`.`albums` (
  `id` INT PRIMARY KEY AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `year` INT NOT NULL,
  `rank` INT NOT NULL,
  `album_type_id` INT NOT NULL,
  INDEX `fk_albums_album_types_idx` (`album_type_id` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  CONSTRAINT `fk_albums_album_types`
    FOREIGN KEY (`album_type_id`)
    REFERENCES `photo_album`.`album_types` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `photo_album`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `photo_album`.`users` (
  `user_id` INT PRIMARY KEY AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `admin` INT NOT NULL,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `photo_album`.`pictures`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `photo_album`.`pictures` (
  `id` INT PRIMARY KEY AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `album_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  INDEX `fk_pictures_albums1_idx` (`album_id` ASC),
  UNIQUE INDEX `Name_UNIQUE` (`Name` ASC),
  INDEX `fk_pictures_users1_idx` (`user_id` ASC),
  CONSTRAINT `fk_pictures_albums1`
    FOREIGN KEY (`album_id`)
    REFERENCES `photo_album`.`albums` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pictures_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `photo_album`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
